version: '2'

services:
  waggle:
      restart: always
      build:
        context: .
        dockerfile: ./docker/waggle/Dockerfile
      volumes:
        - .:/django
  webpackdev:
    restart: always
    build:
      context: .
      dockerfile: ./docker/webpackdev/Dockerfile
    volumes:
      - .:/django
  django:
      restart: always
      build:
        context: .
        dockerfile: ./docker/django/Dockerfile
      volumes:
        - .:/django
  postgres:
      restart: always
      image: postgres:9.5.4
      expose:
        - 5432
      volumes:
        - ./docker/postgres/data:/var/lib/postgresql
  nginx:
      restart: always
      image: nginx:1.11.6-alpine
